[package]
name = "rnn"
version = "0.1.0"
authors = ["Vladimír Ctibor <vladimir.malky@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.4"
rand_distr = "0.4.1"
flate2 = "1.0.20"
byteorder = "1.4.3"

[profile.release]
debug = true